  on:
    workflow_dispatch
  
  env:
    targetEnv: test
  
  name: Azure Bicep
  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
        packages: write
      steps:
      # Checkout code
      - uses: actions/checkout@main
  
        # Log into Azure
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          enable-AzPSSession: true
          auth-type: SERVICE_PRINCIPAL
  
        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./InfrastructureAsCode/main.bicep
          parameters: environment=${{ env.targetEnv }}